(part "PC817X3NIP1B"
    (packageRef "SOP254P960X420-4N")
    (interface
        (port "1" (symbPinId 1) (portName "ANODE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CATHODE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EMITTER") (portType INOUT))
        (port "4" (symbPinId 4) (portName "COLLECTOR") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Sharp Microelectronics")
    (property "Manufacturer_Part_Number" "PC817X3NIP1B")
    (property "Mouser_Part_Number" "852-PC817X3NIP1B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Sharp-Microelectronics/PC817X3NIP1B?qs=rrS6PyfT74f4G0G4E3ul%2FQ%3D%3D")
    (property "Arrow_Part_Number" "PC817X3NIP1B")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/pc817x3nip1b/sharp.html?utm_currency=USD&region=europe")
    (property "Description" "Transistor Output Optocouplers OPTOISOLATOR 5KV TRANS SMD, Optoisolator Transistor Output 1 Channel")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/6722695ec663e8d5f4c0406356e05a32.pdf")
    (property "symbolName1" "PC817X3NIP1B")
)
