use axum::{
    extract::State,
    response::{Html, IntoResponse, Json},
    routing::{get, post},
    Router,
};
use serde::{Deserialize, Serialize};
use std::{net::SocketAddr, sync::Arc, time::Instant};
use tokio::sync::Mutex;
use tower_http::cors::CorsLayer;

// ============================================================
// DATA STRUCTURES
// ============================================================

#[derive(Clone)]
struct AppState {
    /// IP of ESP32-S3 Master (hub connects to this to pull data)
    esp_s3_ip: Arc<Mutex<String>>,
    /// IP of ESP32 WROOM Slave (for direct fallback or OTA proxy)
    esp_wroom_ip: Arc<Mutex<String>>,
    /// Latest live reading from ESP32-S3 (cached by background poller)
    latest_reading: Arc<Mutex<LiveReading>>,
    /// Smart alerts generated by analysis engine
    alerts: Arc<Mutex<Vec<SmartAlert>>>,
    /// Weather cache
    weather_cache: Arc<Mutex<Option<WeatherData>>>,
    weather_last_fetch: Arc<Mutex<Option<Instant>>>,
    /// Rolling telemetry history (max 60 samples for charts)
    telemetry_history: Arc<Mutex<Vec<TelemetrySample>>>,
}

/// The single unified data structure Flutter receives from /api/status
#[derive(Serialize, Deserialize, Clone, Debug)]
struct LiveReading {
    is_online: bool,
    voltage: f64,
    current: f64,
    power: f64,
    energy: f64,
    frequency: f64,
    pf: f64,
    last_update_ts: u64,
}

impl Default for LiveReading {
    fn default() -> Self {
        Self {
            is_online: false,
            voltage: 0.0, current: 0.0, power: 0.0, energy: 0.0,
            frequency: 50.0, pf: 1.0, last_update_ts: 0,
        }
    }
}

#[derive(Serialize, Clone, Debug)]
struct SmartAlert {
    level: String,
    icon: String,
    title: String,
    message: String,
    timestamp: u64,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
struct WeatherData {
    city: String,
    temp: f64,
    feels_like: f64,
    humidity: u32,
    description: String,
    icon: String,
    wind_speed: f64,
    suggestion: String,
}

#[derive(Serialize, Clone, Debug)]
struct TelemetrySample {
    voltage: f64,
    current: f64,
    power: f64,
    energy: f64,
    frequency: f64,
    pf: f64,
    timestamp: u64,
}

#[derive(Deserialize)]
struct ConfigPayload {
    esp_s3_ip: Option<String>,
    esp_wroom_ip: Option<String>,
}

// ============================================================
// MAIN
// ============================================================

#[tokio::main]
async fn main() {
    println!("🦀 DTV Energy Smart Hub — Rust Core Server");
    println!("   Architecture: App ──> Rust Server ──> ESP32-S3 ──> WROOM");
    println!();

    let state = AppState {
        esp_s3_ip: Arc::new(Mutex::new("192.168.11.181".to_string())),
        esp_wroom_ip: Arc::new(Mutex::new("192.168.11.182".to_string())),
        latest_reading: Arc::new(Mutex::new(LiveReading::default())),
        alerts: Arc::new(Mutex::new(Vec::new())),
        weather_cache: Arc::new(Mutex::new(None)),
        weather_last_fetch: Arc::new(Mutex::new(None)),
        telemetry_history: Arc::new(Mutex::new(Vec::new())),
    };

    // Spawn background poller (ESP32-S3 → Rust every 5s)
    let bg = state.clone();
    tokio::spawn(async move { background_poller(bg).await; });

    let app = Router::new()
        .route("/", get(serve_ui))
        // === UNIFIED API — Flutter, Web UI, Google Assistant & Android App OTA ===
        .route("/api/status", get(handle_status))       // Live metrics (cached)
        .route("/api/data", get(handle_status))         // Legacy UI alias
        .route("/api/alerts", get(handle_alerts))        // Smart alerts
        .route("/api/weather", get(handle_weather))      // Weather Hà Nội
        .route("/api/analytics", get(handle_analytics))  // Chart history
        .route("/api/config", post(handle_config))       // Set ESP IPs
        .route("/api/config", get(handle_get_config))    // Get ESP IPs (for OTA)
        .route("/api/google-assistant", post(handle_google_assistant)) // Google Assistant webhook
        .route("/api/app-version", get(handle_app_version)) // Android App OTA version check
        .route("/downloads/app-debug.apk", get(serve_apk))   // Android App APK download
        .layer(CorsLayer::permissive())
        .with_state(state);

    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));
    println!("🚀 Server running at http://0.0.0.0:8080");
    println!("   GET  /api/status    → Live voltage/current/power/energy");
    println!("   GET  /api/alerts    → Smart alerts & tips");
    println!("   GET  /api/weather   → Hà Nội weather");
    println!("   GET  /api/analytics → 60-sample chart history");
    println!("   POST /api/config    → Set ESP32 IPs");
    println!("   GET  /api/config    → Get ESP32 IPs (for OTA targets)");
    println!();

    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

// ============================================================
// BACKGROUND POLLER — pulls data from ESP32-S3 every 5s
// ============================================================

async fn background_poller(state: AppState) {
    println!("📊 Background Poller started (5s cycle)");
    println!("   Polling ESP32-S3 for PZEM data via ESP-NOW relay...");

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_millis(2500))
        .build()
        .unwrap();

    loop {
        tokio::time::sleep(std::time::Duration::from_secs(5)).await;

        let s3_ip = state.esp_s3_ip.lock().await.clone();
        let wroom_ip = state.esp_wroom_ip.lock().await.clone();

        let now_ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        // Try ESP32-S3 /api/status first, then /data, then WROOM /data
        let urls = vec![
            format!("http://{}/api/status", s3_ip.trim()),
            format!("http://{}/data", s3_ip.trim()),
            format!("http://{}/data", wroom_ip.trim()),
        ];

        let mut got_data = false;

        for url in &urls {
            if let Ok(resp) = client.get(url).send().await {
                if let Ok(json) = resp.json::<serde_json::Value>().await {
                    let voltage = parse_num(&json, "voltage");
                    let current = parse_num(&json, "current");
                    let power = parse_num(&json, "power");
                    let energy = parse_num(&json, "energy");
                    let frequency = parse_num_or(&json, "frequency", 50.0);
                    let pf = parse_num_or(&json, "pf", 1.0);

                    // Update latest reading
                    {
                        let mut reading = state.latest_reading.lock().await;
                        reading.is_online = true;
                        reading.voltage = voltage;
                        reading.current = current;
                        reading.power = power;
                        reading.energy = energy;
                        reading.frequency = frequency;
                        reading.pf = pf;
                        reading.last_update_ts = now_ts;
                    }

                    // Push to telemetry history (rolling 60)
                    {
                        let mut history = state.telemetry_history.lock().await;
                        history.push(TelemetrySample {
                            voltage, current, power, energy, frequency, pf,
                            timestamp: now_ts,
                        });
                        if history.len() > 60 { history.remove(0); }
                    }

                    // Run alert engine
                    run_alert_engine(&state, voltage, current, power, pf, now_ts).await;

                    println!("✅ [{:.0}V {:.2}A {:.0}W] from {}", voltage, current, power, url);
                    got_data = true;
                    break; // Got data, stop trying other URLs
                }
            }
        }

        if !got_data {
            // Mark offline
            let mut reading = state.latest_reading.lock().await;
            reading.is_online = false;
            println!("❌ No data from S3({}) or WROOM({})", s3_ip, wroom_ip);
        }
    }
}

/// Parse a JSON value that could be a string or number
fn parse_num(json: &serde_json::Value, key: &str) -> f64 {
    json.get(key)
        .map(|v| {
            if let Some(n) = v.as_f64() { n }
            else if let Some(s) = v.as_str() { s.parse::<f64>().unwrap_or(0.0) }
            else { 0.0 }
        })
        .unwrap_or(0.0)
}

fn parse_num_or(json: &serde_json::Value, key: &str, default: f64) -> f64 {
    let v = parse_num(json, key);
    if v == 0.0 { default } else { v }
}

// ============================================================
// SMART ALERT ENGINE
// ============================================================

async fn run_alert_engine(state: &AppState, voltage: f64, _current: f64, power: f64, pf: f64, now_ts: u64) {
    let mut new_alerts: Vec<SmartAlert> = Vec::new();

    // 1. Voltage anomaly
    if voltage > 10.0 && voltage < 200.0 {
        new_alerts.push(SmartAlert {
            level: "critical".into(), icon: "⚠️".into(),
            title: "Điện áp thấp bất thường!".into(),
            message: format!("Điện áp hiện tại {:.1}V < 200V. Kiểm tra nguồn điện!", voltage),
            timestamp: now_ts,
        });
    } else if voltage > 240.0 {
        new_alerts.push(SmartAlert {
            level: "critical".into(), icon: "⚡".into(),
            title: "Điện áp cao bất thường!".into(),
            message: format!("Điện áp {:.1}V > 240V. Tắt thiết bị nhạy cảm!", voltage),
            timestamp: now_ts,
        });
    }

    // 2. High power
    if power > 2000.0 {
        new_alerts.push(SmartAlert {
            level: "warning".into(), icon: "🔥".into(),
            title: "Công suất tiêu thụ cao!".into(),
            message: format!("Đang tiêu thụ {:.0}W. Kiểm tra máy lạnh, bếp điện.", power),
            timestamp: now_ts,
        });
    }

    // 3. Low power factor
    if pf < 0.8 && pf > 0.0 {
        new_alerts.push(SmartAlert {
            level: "warning".into(), icon: "📉".into(),
            title: "Hệ số công suất thấp".into(),
            message: format!("PF = {:.2}. Động cơ/quạt gây hao phí.", pf),
            timestamp: now_ts,
        });
    }

    // 4. Trend analysis
    {
        let history = state.telemetry_history.lock().await;
        if history.len() >= 10 {
            let recent = &history[history.len()-10..];
            let first_avg: f64 = recent[..5].iter().map(|s| s.power).sum::<f64>() / 5.0;
            let last_avg: f64 = recent[5..].iter().map(|s| s.power).sum::<f64>() / 5.0;
            if last_avg > first_avg * 1.3 && last_avg > 100.0 {
                new_alerts.push(SmartAlert {
                    level: "info".into(), icon: "📈".into(),
                    title: "Xu hướng tăng tiêu thụ".into(),
                    message: format!("Công suất tăng từ {:.0}W → {:.0}W trong 50s qua.", first_avg, last_avg),
                    timestamp: now_ts,
                });
            }
        }
    }

    // 5. Energy saving tip
    if power < 500.0 && power > 0.0 {
        new_alerts.push(SmartAlert {
            level: "tip".into(), icon: "💡".into(),
            title: "Gợi ý tiết kiệm điện".into(),
            message: "Tiêu thụ ổn định. Tắt đèn và thiết bị không dùng để tiết kiệm thêm!".into(),
            timestamp: now_ts,
        });
    }

    *state.alerts.lock().await = new_alerts;
}

// ============================================================
// API HANDLERS — Flutter calls ONLY these
// ============================================================

/// GET /api/status — returns latest cached reading (no direct ESP call)
async fn handle_status(State(state): State<AppState>) -> impl IntoResponse {
    let reading = state.latest_reading.lock().await.clone();
    Json(reading)
}

/// GET /api/alerts — smart alerts
async fn handle_alerts(State(state): State<AppState>) -> impl IntoResponse {
    let alerts = state.alerts.lock().await.clone();
    Json(alerts)
}

/// GET /api/analytics — telemetry chart history
async fn handle_analytics(State(state): State<AppState>) -> impl IntoResponse {
    let history = state.telemetry_history.lock().await.clone();
    Json(history)
}

/// GET /api/weather — Hà Nội weather with energy tips
async fn handle_weather(State(state): State<AppState>) -> impl IntoResponse {
    // Check cache (15 min TTL)
    let should_fetch = {
        let last = state.weather_last_fetch.lock().await;
        match *last {
            Some(t) => t.elapsed().as_secs() > 900,
            None => true,
        }
    };

    if should_fetch {
        if let Ok(client) = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(5)).build()
        {
            let url = "https://api.openweathermap.org/data/2.5/weather?q=Hanoi&appid=demo&units=metric&lang=vi";
            if let Ok(resp) = client.get(url).send().await {
                if let Ok(json) = resp.json::<serde_json::Value>().await {
                    let temp = json["main"]["temp"].as_f64().unwrap_or(32.0);
                    let feels = json["main"]["feels_like"].as_f64().unwrap_or(35.0);
                    let humidity = json["main"]["humidity"].as_u64().unwrap_or(70) as u32;
                    let desc = json["weather"][0]["description"].as_str().unwrap_or("trời nắng").to_string();
                    let icon = json["weather"][0]["icon"].as_str().unwrap_or("01d").to_string();
                    let wind = json["wind"]["speed"].as_f64().unwrap_or(3.0);

                    let suggestion = if temp > 35.0 {
                        "Trời nóng! Máy lạnh tiêu thụ nhiều điện. Đặt 26°C để tiết kiệm.".into()
                    } else if temp > 30.0 {
                        "Thời tiết ấm áp. Dùng quạt thay máy lạnh để tiết kiệm điện.".into()
                    } else if desc.contains("mưa") {
                        "Trời mưa, độ ẩm cao. Hạn chế dùng máy sấy quần áo.".into()
                    } else {
                        "Thời tiết dễ chịu. Mở cửa sổ thay vì dùng máy lạnh!".into()
                    };

                    let weather = WeatherData {
                        city: "Hà Nội".into(), temp, feels_like: feels, humidity,
                        description: desc, icon, wind_speed: wind, suggestion,
                    };
                    *state.weather_cache.lock().await = Some(weather);
                    *state.weather_last_fetch.lock().await = Some(Instant::now());
                }
            }
        }
    }

    let cache = state.weather_cache.lock().await.clone();
    let weather = cache.unwrap_or(WeatherData {
        city: "Hà Nội".into(), temp: 32.0, feels_like: 35.0, humidity: 70,
        description: "trời nắng".into(), icon: "01d".into(), wind_speed: 3.5,
        suggestion: "Thời tiết ấm áp. Dùng quạt thay máy lạnh để tiết kiệm điện.".into(),
    });

    Json(weather)
}

/// POST /api/config — set ESP32 IPs from app Settings
async fn handle_config(
    State(state): State<AppState>,
    Json(payload): Json<ConfigPayload>,
) -> impl IntoResponse {
    if let Some(ip) = payload.esp_s3_ip {
        if !ip.trim().is_empty() {
            *state.esp_s3_ip.lock().await = ip.clone();
            println!("📌 ESP32-S3 IP updated to: {}", ip);
        }
    }
    if let Some(ip) = payload.esp_wroom_ip {
        if !ip.trim().is_empty() {
            *state.esp_wroom_ip.lock().await = ip.clone();
            println!("📌 WROOM IP updated to: {}", ip);
        }
    }
    Json(serde_json::json!({"status": "ok"}))
}

/// GET /api/config — return current ESP IPs (for OTA target selection)
async fn handle_get_config(State(state): State<AppState>) -> impl IntoResponse {
    let s3 = state.esp_s3_ip.lock().await.clone();
    let wroom = state.esp_wroom_ip.lock().await.clone();
    Json(serde_json::json!({
        "esp_s3_ip": s3,
        "esp_wroom_ip": wroom,
    }))
}

/// GET / — Web UI
async fn serve_ui() -> impl IntoResponse {
    Html(include_str!("index.html"))
}

// ============================================================
// GOOGLE ASSISTANT & VOICE WEBHOOK
// ============================================================

#[derive(Deserialize)]
struct GoogleAssistantRequest {
    intent: Option<String>,
}

#[derive(Serialize)]
struct GoogleAssistantResponse {
    speech_response: String,
    status: String,
    voltage: f64,
    power: f64,
    energy: f64,
}

/// POST /api/google-assistant — Webhook for Google Assistant Actions & Voice Intent Query
async fn handle_google_assistant(
    State(state): State<AppState>,
    Json(payload): Json<GoogleAssistantRequest>,
) -> impl IntoResponse {
    let reading = state.latest_reading.lock().await.clone();
    let intent = payload.intent.unwrap_or_else(|| "query_status".to_string());

    let speech = match intent.as_str() {
        "query_voltage" => format!("Điện áp mạng điện nhà bạn hiện tại là {:.1} Volts.", reading.voltage),
        "query_power" => format!("Công suất tiêu thụ điện năng tức thời hiện tại là {:.0} Watts.", reading.power),
        "query_energy" => format!("Tổng điện năng tích lũy đã tiêu thụ là {:.2} Kilo-Watt giờ.", reading.energy),
        "query_pf" => format!("Hệ số công suất Power Factor hiện tại là {:.2}.", reading.pf),
        _ => if reading.is_online {
            format!("Hệ thống điện DTV Energy hoạt động bình thường. Điện áp: {:.1} Volts, Công suất: {:.0} Watts.", reading.voltage, reading.power)
        } else {
            "Cảnh báo: Hiện chưa nhận được dữ liệu từ cảm biến đo điện năng ESP32.".to_string()
        },
    };

    Json(GoogleAssistantResponse {
        speech_response: speech,
        status: "SUCCESS".to_string(),
        voltage: reading.voltage,
        power: reading.power,
        energy: reading.energy,
    })
}

// ============================================================
// ANDROID APP OTA UPDATE HANDLERS
// ============================================================

#[derive(Serialize)]
struct AppVersionResponse {
    version: String,
    build_number: u32,
    apk_url: String,
    changelog: String,
}

/// GET /api/app-version — returns latest Android App version info
async fn handle_app_version() -> impl IntoResponse {
    Json(AppVersionResponse {
        version: "1.0.5".to_string(),
        build_number: 5,
        apk_url: "/downloads/app-debug.apk".to_string(),
        changelog: "🔥 Nâng cấp v1.0.5: Tích hợp công cụ Tính Tiền Điện EVN Bậc Thang 2026, tối ưu kết nối Rust Gateway & Nạp App OTA!".to_string(),
    })
}

/// GET /downloads/app-debug.apk — serves static Android APK file for in-app OTA download
async fn serve_apk() -> impl IntoResponse {
    let apk_path = "/home/tuan/SIC_Project/dtv_energy_flutter/build/app/outputs/flutter-apk/app-debug.apk";
    match tokio::fs::read(apk_path).await {
        Ok(bytes) => (
            [
                ("Content-Type", "application/vnd.android.package-archive"),
                ("Content-Disposition", "attachment; filename=\"dtv_energy_v1.0.1.apk\""),
            ],
            bytes,
        ).into_response(),
        Err(_) => (
            axum::http::StatusCode::NOT_FOUND,
            "APK file not found on server",
        ).into_response(),
    }
}
