(part "B0505S-2W"
    (packageRef "B0505S2W")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 3) (portName "0V") (portType INOUT))
        (port "6" (symbPinId 4) (portName "+VO") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Mornsun Power")
    (property "Manufacturer_Part_Number" "B0505S-2W")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "2W isolated DC-DC converter Fixed input voltage, 5VDC, 400 mA unregulated single output")
    (property "Datasheet_Link" "https://www.mornsun-power.com/html/pdf/B0505S-2WR3.html")
    (property "symbolName1" "B0505S-2W")
)
