(part "HF32FA-G_005-HSL1"
    (packageRef "HF32FAG005HSL1")
    (interface
        (port "1" (symbPinId 1) (portName "COIL_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO") (portType INOUT))
        (port "4" (symbPinId 4) (portName "COIL_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "161")
    (property "Manufacturer_Name" "Hongfa")
    (property "Manufacturer_Part_Number" "HF32FA-G/005-HSL1")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "HF32FA Series 10 A SPST 5 V Sealed Subminiature Intermediate Power Relay")
    (property "Datasheet_Link" "")
    (property "symbolName1" "HF32FA-G_005-HSL1")
)
